---
title: "IS609 -Math Modeling - HW4"
author: "J. Hamski"
date: "February 25, 2016"
output: html_document
---

*Packages Used*
```{r}
library(ggplot2)
library(knitr)
```

###1

```{r}
quarter.circle <- function(){
  x <- runif(1, 0.0, 1.0)
  y <- runif(1, 0.0, 1.0)
  Q <- 1 > x**2 + y**2
  return(Q)}

iter <- 10000

circle.inout <- replicate(iter, quarter.circle())

circle.out <- sum(circle.inout, na.rm=TRUE)

pi.estimate <- circle.out / iter * 4

pi.estimate
```

###2

This would have been simpler in Python...
```{r}
middle.sq <- function(seed){
  square <- seed ** 2
  square.len <- nchar(square, type="chars")
  square <- toString(square)
  square <-ifelse(square.len %%2 == 0, square, paste("0", square, sep = ""))
  
  square.len <- nchar(square, type="chars")
  seed.len <- nchar(seed, type = "chars")
  
  start <- (square.len / 2) - 1
  stop <- (square.len) / 2 + 1
  
  next.num <- substr(square, start, stop)
  next.num <- as.numeric(next.num)
  return(next.num)
}

# I always have a hard time doing recursive functions in R...

seed = 2041
for (i in 1:12){
  new <- middle.sq(seed[i])
  seed <- c(seed, new)
}


```

```{r}
#a
seed = 1009
for (i in 1:12){
  new <- middle.sq(seed[i])
  seed <- c(seed, new)
}
seed
```


```{r}
#b
seed = 653217
for (i in 1:12){
  new <- middle.sq(seed[i])
  seed <- c(seed, new)
}
seed
```


```{r}
#c
seed = 3043
for (i in 1:12){
  new <- middle.sq(seed[i])
  seed <- c(seed, new)
}

seed
```



###3

```{r}

odds <- c(1/7, 1/5, 1/9, 1/12, 1/4, 1/35, 1/15, 1/4)
horses <- as.factor(c("EF", "LL", "NL", "CC", "PuP", "LLH", "SS", "DD"))

races = 1000

race.simulation <- sample(x = horses, size = races, prob = odds, replace = T)

summary(race.simulation)
```

Dancing Dantzig won the most races - but each time I run the simulation it is different, Pumped up Poisson could win as well. Loping L'Hopital won the fewwest races. These results don't suprise me at all, as the simulation, and therefore the rankings, follow directly from the odds. 

###4
```{r}
lag.times <- as.factor(2:7)
lag.prob <- c(0.1, 0.25, 0.3, 0.2, 0.13, 0.02)

trials = 1000

lag.simulation <- sample(x = lag.times, size = trials, prob = lag.prob, replace = T)
lag.results <- as.data.frame(table(lag.simulation))

lag.results <- cbind(lag.results, lag.prob)

new.names <- c("Lag_Time", "Simulated", "Actual")
colnames(lag.results) <- new.names

lag.results$Simulated <- lag.results$Simulated / trials

lag.results$Difference <- abs(lag.results$Actual - lag.results$Simulated)

kable(lag.results)
```


###5
```{r}



```

