---
title: "Homework - Ch. 13"
author: "J. Hamski"
date: "April 24, 2016"
output: html_document
---

### 1 
*What conditions might argue for allowing a temporarily out of stock policy?*  
  
Extremely high storage costs would act as a disincentive for storing the stock at high enough levels to prevent stock-outs.   
  
*What effect does this policy have on storage costs?*  

It reduces storage costs, especially if there is a high level of variability in demand that would necissitate potentially storing a lot more stock than you would actually sell in short time intervals.   

*Should costs be assigned to stock-outs? Why?*  

Stock-outs will result fewer orders being filled, since customers may seek out a competitor or subsiute instead of waiting for the restock.   
  
*How would you make such an assignment?*  

There would need to be a loss-factor I would call 'missed sales = m'. The loss-factor m would be a cost like s and d. 

*What assumptions are implied by the model in Fig. 13.7?*

Stock-outs will be remedied at a certain level and be built back up

*Suppose a "loss of goodwill cost" of w dollars per day is assigned to each stock-out. Compute the optimal order quantity Q and interpret your model.*

The optimal quantity is when the cost from stock-outs is less than the storage costs of keeping enough stock to prevent stockouts. The delivery cost is constant in either scenario. Therefore the model is:

$$minimize c = \frac{d}{t} + \frac{srtm}{2}$$
$$subject to:$$
$$m<s$$



### 2

```{r}

min.soln <- function(x,y){
  min <- 3*x^2 + 6*x*y + 7*y^2 - 2*x + 4*y
  return(min)
}

min.soln(1.083, -0.75)
```


### 3


### 4


### 5



